export const NORMALIZED_STATUS = Object.freeze({
  PENDING: 'pending',
  RUNNING: 'running',
  SUCCEEDED: 'succeeded',
  RETRYABLE_FAILED: 'retryable_failed',
  TERMINAL_FAILED: 'terminal_failed',
  SKIPPED: 'skipped',
  UNCERTAIN: 'uncertain',
});

export const REPLY_RAW_STATUS = Object.freeze({
  PENDING: 'pending',
  PREPARED: 'prepared',
  SUCCEEDED: 'succeeded',
  SENT_UNVERIFIED: 'sent_unverified',
  BLOCKED: 'blocked',
  SKIPPED: 'skipped',
  MANUALLY_REPLIED: 'manually_replied',
});

export const VISIT_TASK_RAW_STATUS = Object.freeze({
  PENDING_VISIT: 'pending_visit',
  COLLECTING_CONTENT: 'collecting_content',
  CONTENT_COLLECTED: 'content_collected',
  COMMENT_GENERATED: 'comment_generated',
  PENDING_EXECUTE: 'pending_execute',
  EXECUTING: 'executing',
  DONE: 'done',
  SKIPPED_NO_WORK: 'skipped_no_work',
  SKIPPED_PRIVATE: 'skipped_private',
  SKIPPED_NO_SUITABLE_WORK: 'skipped_no_suitable_work',
  FAILED_COLLECT: 'failed_collect',
  FAILED_GENERATE_COMMENT: 'failed_generate_comment',
  FAILED_LIKE: 'failed_like',
  FAILED_COMMENT: 'failed_comment',
  FAILED: 'failed',
});

export const INTERACTION_EVENT_RAW_STATUS = Object.freeze({
  NEW: 'new',
  PLANNED: 'planned',
  PREPARED: 'prepared',
  RUNNING: 'running',
  REPLIED: 'replied',
  SUCCEEDED: 'succeeded',
  BLOCKED: 'blocked',
  FAILED: 'failed',
  SKIPPED: 'skipped',
  SENT_UNVERIFIED: 'sent_unverified',
});

const REPLY_STATUS_MAP = new Map([
  [REPLY_RAW_STATUS.PENDING, NORMALIZED_STATUS.PENDING],
  [REPLY_RAW_STATUS.PREPARED, NORMALIZED_STATUS.PENDING],
  [REPLY_RAW_STATUS.SUCCEEDED, NORMALIZED_STATUS.SUCCEEDED],
  [REPLY_RAW_STATUS.MANUALLY_REPLIED, NORMALIZED_STATUS.SUCCEEDED],
  [REPLY_RAW_STATUS.SENT_UNVERIFIED, NORMALIZED_STATUS.UNCERTAIN],
  [REPLY_RAW_STATUS.BLOCKED, NORMALIZED_STATUS.TERMINAL_FAILED],
  [REPLY_RAW_STATUS.SKIPPED, NORMALIZED_STATUS.SKIPPED],
]);

const VISIT_TASK_STATUS_MAP = new Map([
  [VISIT_TASK_RAW_STATUS.PENDING_VISIT, NORMALIZED_STATUS.PENDING],
  [VISIT_TASK_RAW_STATUS.CONTENT_COLLECTED, NORMALIZED_STATUS.PENDING],
  [VISIT_TASK_RAW_STATUS.COMMENT_GENERATED, NORMALIZED_STATUS.PENDING],
  [VISIT_TASK_RAW_STATUS.PENDING_EXECUTE, NORMALIZED_STATUS.PENDING],
  [VISIT_TASK_RAW_STATUS.COLLECTING_CONTENT, NORMALIZED_STATUS.RUNNING],
  [VISIT_TASK_RAW_STATUS.EXECUTING, NORMALIZED_STATUS.RUNNING],
  [VISIT_TASK_RAW_STATUS.DONE, NORMALIZED_STATUS.SUCCEEDED],
  [VISIT_TASK_RAW_STATUS.FAILED_COLLECT, NORMALIZED_STATUS.RETRYABLE_FAILED],
  [VISIT_TASK_RAW_STATUS.FAILED_GENERATE_COMMENT, NORMALIZED_STATUS.RETRYABLE_FAILED],
  [VISIT_TASK_RAW_STATUS.FAILED_LIKE, NORMALIZED_STATUS.RETRYABLE_FAILED],
  [VISIT_TASK_RAW_STATUS.FAILED_COMMENT, NORMALIZED_STATUS.RETRYABLE_FAILED],
  [VISIT_TASK_RAW_STATUS.FAILED, NORMALIZED_STATUS.TERMINAL_FAILED],
  [VISIT_TASK_RAW_STATUS.SKIPPED_NO_WORK, NORMALIZED_STATUS.SKIPPED],
  [VISIT_TASK_RAW_STATUS.SKIPPED_PRIVATE, NORMALIZED_STATUS.SKIPPED],
  [VISIT_TASK_RAW_STATUS.SKIPPED_NO_SUITABLE_WORK, NORMALIZED_STATUS.SKIPPED],
]);

const INTERACTION_EVENT_STATUS_MAP = new Map([
  [INTERACTION_EVENT_RAW_STATUS.NEW, NORMALIZED_STATUS.PENDING],
  [INTERACTION_EVENT_RAW_STATUS.PLANNED, NORMALIZED_STATUS.PENDING],
  [INTERACTION_EVENT_RAW_STATUS.PREPARED, NORMALIZED_STATUS.PENDING],
  [INTERACTION_EVENT_RAW_STATUS.RUNNING, NORMALIZED_STATUS.RUNNING],
  [INTERACTION_EVENT_RAW_STATUS.REPLIED, NORMALIZED_STATUS.SUCCEEDED],
  [INTERACTION_EVENT_RAW_STATUS.SUCCEEDED, NORMALIZED_STATUS.SUCCEEDED],
  [INTERACTION_EVENT_RAW_STATUS.BLOCKED, NORMALIZED_STATUS.TERMINAL_FAILED],
  [INTERACTION_EVENT_RAW_STATUS.FAILED, NORMALIZED_STATUS.TERMINAL_FAILED],
  [INTERACTION_EVENT_RAW_STATUS.SKIPPED, NORMALIZED_STATUS.SKIPPED],
  [INTERACTION_EVENT_RAW_STATUS.SENT_UNVERIFIED, NORMALIZED_STATUS.UNCERTAIN],
]);

function normalizeStatus(rawStatus, statusMap) {
  return statusMap.get(String(rawStatus || '').trim()) || NORMALIZED_STATUS.UNCERTAIN;
}

export function normalizeReplyStatus(rawStatus) {
  return normalizeStatus(rawStatus, REPLY_STATUS_MAP);
}

export function normalizeVisitTaskStatus(rawStatus) {
  return normalizeStatus(rawStatus, VISIT_TASK_STATUS_MAP);
}

export function normalizeInteractionEventStatus(rawStatus) {
  return normalizeStatus(rawStatus, INTERACTION_EVENT_STATUS_MAP);
}

export function isNormalizedTerminalStatus(status) {
  return [
    NORMALIZED_STATUS.SUCCEEDED,
    NORMALIZED_STATUS.TERMINAL_FAILED,
    NORMALIZED_STATUS.SKIPPED,
  ].includes(status);
}

export function isNormalizedRetryableStatus(status) {
  return [
    NORMALIZED_STATUS.PENDING,
    NORMALIZED_STATUS.RUNNING,
    NORMALIZED_STATUS.RETRYABLE_FAILED,
    NORMALIZED_STATUS.UNCERTAIN,
  ].includes(status);
}

export function buildNormalizedStatusDistribution(rows, {
  statusKey = 'status',
  countKey = 'count',
  normalize,
} = {}) {
  const distribution = {
    [NORMALIZED_STATUS.PENDING]: 0,
    [NORMALIZED_STATUS.RUNNING]: 0,
    [NORMALIZED_STATUS.SUCCEEDED]: 0,
    [NORMALIZED_STATUS.RETRYABLE_FAILED]: 0,
    [NORMALIZED_STATUS.TERMINAL_FAILED]: 0,
    [NORMALIZED_STATUS.SKIPPED]: 0,
    [NORMALIZED_STATUS.UNCERTAIN]: 0,
  };

  for (const row of rows || []) {
    const normalized = normalize(row?.[statusKey]);
    const count = Number(row?.[countKey]) || 0;
    distribution[normalized] = (distribution[normalized] || 0) + count;
  }

  return distribution;
}
